name: Test and Release

on:
  push:

env:
  # For chalk: https://github.com/chalk/chalk#supportscolor
  FORCE_COLOR: 3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Run Unit Tests
        run: npm test

      - name: Parse examples
        run: |
          npx tsx parse.ts parser/test-data/feature/Example.feature.md
          npx tsx parse.ts parser/test-data/feature/Highlander.feature.md
          npx tsx parse.ts examples/mars-rover/MarsRover.feature.md

      - name: Run examples
        run: |
          npx tsx examples/mars-rover/tests.ts
          npx tsx examples/firmware/tests.ts

      - name: Semantic release
        continue-on-error: true
        run: npx semantic-release
